import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Toaster } from "sonner";
import React, { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
	modal
}: Readonly<{
	children: React.ReactNode;
	modal: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className} suppressHydrationWarning>
				<Providers>
					<Toaster
						richColors
						duration={5000}
						closeButton
						position="top-center"
					/>
					<Suspense fallback={<>loading...</>}>
						{children} {modal}
					</Suspense>
				</Providers>
				<div id="modal-root" />
			</body>
		</html>
	);
}
