import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { MetaMaskProvider } from "@metamask/sdk-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sdkOptions = {
  dappMetadata: {
    name: "Example React Dapp",
    // url: window.location.href,
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning>
        {/* <MetaMaskProvider debug={false} sdkOptions={sdkOptions}> */}
          <Providers>
            {children}
          </Providers>
        {/* </MetaMaskProvider> */}
      </body>
    </html>
  );
}
